AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template example

Globals:
    Function:
        Timeout: 120


Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: com.binaryheap.lambdatest.FunctionHandler::handleRequest
            Runtime: java8
            CodeUri: target/lambda-test-1.0-SNAPSHOT.jar
            MemorySize: 512